### ISSUE TITLE
A way to pass function pointers to a FFI function (bridge)

### ISSUE THREAD

**Issue by its-darsh** [syphon-lang/syphon#34]
Since Python already supports [callback functions](https://docs.python.org/3/library/ctypes.html#callback-functions), it would be great to have support for begin able to pass a function _reference_ from Syphon over to FFI functions.

**Comment by yhyadev** [comment]
Because we use libffi, I took a look into the documentation a little bit and found there is libffi closure that does exactly what we need to make ffi callbacks work

**Comment by yhyadev** [comment]
I will try to implement what the issue described with a simple syntax

**Comment by yhyadev** [comment]
Was refactor a little bit before I start implementing this

Here is the syntax I settled on:

```
print_i = fn (i) {
    print(i)
}

ffi.callback(print_i, {
    "parameters": [ffi.types.i32],
    "returns": ffi.types.void,
})
```

**Comment by yhyadev** [comment]
a slight change because callbacks should be freed (they allocate writeable and executable memories using libffi and not the garbage collector)

```
print_i = fn (i) {
    print(i)
}

print_i_callback = ffi.allocate_callback(print_i, {
    "parameters": [ffi.types.i32],
    "returns": ffi.types.void,
})

ffi.free_callback(print_i_callback)
```
